version: "3"

services:
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.production
    container_name: ${PROJECT_NAME}-dashboard
    command: npm run dev
    environment:
      - WDS_SOCKET_PORT=0
      - PORT=8080
    stdin_open: true
    tty: true
    volumes:
      - ./dashboard/src:/usr/src/app/src
    restart: unless-stopped
    networks:
      - mohirdev-docker-network
    depends_on:
      - backend
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: ${PROJECT_NAME}-docker-api
    command: npm run start:dev
    volumes:
      - "./backend:/usr/src/app"
      - "node_modules:/usr/src/app/node_modules"
    restart: unless-stopped
    environment:
      - PORT=3001
      - HOST=http://localhost:3001
      - MONGO_URL=mongodb://api_db:27017/api
      - SECRET_KEY=mysecretkey
    depends_on:
      - db
    networks:
      - mohirdev-docker-network

  db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: mydatabase
      POSTGRES_PORT: 5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/backups:/backups
      - ./db/logs:/var/log
    ports:
      - "5432:5432"

  nginx:
    image: nginx:stable-alpine
    container_name: ${PROJECT_NAME}-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - dashboard
      - backend
    networks:
      - mohirdev-docker-network

volumes:
  mohirdev_mongodb_api:
  node_modules:
networks:
  mohirdev-docker-network:
    driver: bridge
