name: Basic CI

on:
  push:
    branches:
      - stage

jobs:
  check-runner:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, World! The runner is working!"
