name: Basic CI

on:
  push:
    branches:
      - stage

jobs:
  check-runner:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: ls -al

      - name: Print location of project
        run: pwd

      - name: Print git branch version
        run: git branch -v

      - name: Build Docker Compose Services
        env:
          PROJECT_NAME: rnpp
          BACKEND_HOST: https://mohirdev-docker.stage
          BACKEND_SECRET_KEY: mysecretkey
          DB_USER: user
          DB_PASSWORD: 12345678
          DB_NAME: mydatabase
          PG_ADMIN_EMAIL: admin@admin.com
          PG_ADMIN_PASSWORD: admin
          PG_ADMIN_PORT: 80
        run: docker-compose -f docker-compose.yml build

      - name: Deploy to Server
        env:
          PROJECT_NAME: rnpp
          BACKEND_HOST: https://mohirdev-docker.stage
          BACKEND_SECRET_KEY: mysecretkey
          DB_USER: user
          DB_PASSWORD: 12345678
          DB_NAME: mydatabase
          PG_ADMIN_EMAIL: admin@admin.com
          PG_ADMIN_PASSWORD: admin
          PG_ADMIN_PORT: 80
        run: |
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml up -d

      - name: Run database migration
        env:
          PROJECT_NAME: rnpp
          BACKEND_HOST: https://mohirdev-docker.stage
          BACKEND_SECRET_KEY: mysecretkey
          DB_USER: user
          DB_PASSWORD: 12345678
          DB_NAME: mydatabase
          PG_ADMIN_EMAIL: admin@admin.com
          PG_ADMIN_PASSWORD: admin
          PG_ADMIN_PORT: 80
        run: docker-compose exec backend npx prisma migrate deploy
