name: Basic CI

on:
  push:
    branches:
      - stage

jobs:
  check-runner:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: ls -al

      - name: Print location of project
        run: pwd

      - name: Print git branch version
        run: git branch -v

      - name: Build Docker Compose Services
        run: docker-compose -f docker-compose.yml build

      - name: Deploy to Server
        run: |
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml up -d
